name: keep-render-warm

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health
        run: |
          URL="https://api.savingharbor.com/public/v1/health"
          echo "Pinging $URL"
          sleep $((RANDOM % 20))
          if curl -fsS -m 10 "$URL" -o /dev/null; then
            echo "OK: $URL"
          else
            echo "FAIL: $URL"
          fi
